import{MAPBOX_TOKEN,firebaseConfig}from'./config.js';
const $=(s,r=document)=>r.querySelector(s),panel=$('#panel'),st={page:'explore',mode:'point',waypoints:[],names:[],routes:[],selected:null,markers:[],nodes:[],layers:[],weatherOn:false,weather:null,geocoders:{},poiMarkers:[],cycleLayer:false,user:null,auth:null,login:null,logout:null,wind:{speed:15,dir:240},previewTimer:null,previewRun:0,routeBatch:0};
const mobile=()=>innerWidth<761,toast=t=>{let e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)},fmt=n=>Number(n||0).toFixed(1),store={get:(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k))||d}catch{return d}},set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
mapboxgl.accessToken=MAPBOX_TOKEN;const map=new mapboxgl.Map({container:'map',style:'mapbox://styles/mapbox/outdoors-v12',center:[-2.5879,51.4545],zoom:11,preserveDrawingBuffer:true});map.addControl(new mapboxgl.NavigationControl(),'top-right');
const NAV=[['explore','⌂'],['journey','↔'],['adventure','◌'],['routes','▤'],['activities','▥'],['weather','☁'],['profile','●']];$('#nav').insertAdjacentHTML('beforeend',NAV.map(([p,i])=>`<button class="nav" data-p="${p}"><i>${i}</i><small>${p[0].toUpperCase()+p.slice(1)}</small></button>`).join(''));$('#nav').onclick=e=>{let b=e.target.closest('[data-p]');if(b)open(b.dataset.p)};
function stopPreview(){st.previewRun++;if(st.previewTimer)clearTimeout(st.previewTimer);st.previewTimer=null;map.stop();if(map.getPitch()>10)map.easeTo({pitch:0,bearing:0,duration:300})}
function open(p){stopPreview();st.page=p;document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.p===p));document.body.classList.toggle('panel-open',p!=='explore'||!mobile());render();setTimeout(()=>map.resize(),40)}
function head(t,s){return`<div class="head"><div><h1>${t}</h1><p>${s}</p></div><button class="close">×</button></div>`}function bind(){const b=$('.close');if(b)b.onclick=()=>open('explore');panel.querySelectorAll('button').forEach(b=>b.addEventListener('click',e=>{if(!e.currentTarget.matches('#preview3d'))stopPreview()},{capture:true}))}
function render(){({explore,journey,adventure,routes,activities,weather,profile}[st.page]||explore)();bind()}
function explore(){panel.innerHTML=head('Explore','Find a route even when you do not know where to go')+`<div class="card hero"><h2>Adventure route generator</h2><p>Build a scenic loop around views, landmarks and food, or plan a normal point-to-point ride.</p><div class="actions"><button class="btn green" id="loop">Create a loop</button><button class="btn light" id="point">Point to point</button></div></div>`;$('#loop').onclick=()=>open('adventure');$('#point').onclick=()=>open('journey')}
function journey(){st.mode='point';panel.innerHTML=head('Point-to-point','Choose a start and finish to compare recommended cycling routes')+`<div class="card"><div class="field"><label>Start</label><div class="location-row"><div id="g0" class="location-search"></div><button id="startHere" class="loc-btn" title="Use current location for start">◎</button></div></div><div class="field"><label>Finish</label><div class="location-row"><div id="g1" class="location-search"></div><button id="finishHere" class="loc-btn" title="Use current location for finish">◎</button></div></div><div class="actions"><button class="btn light" id="more" style="display:${st.routes.length?'inline-flex':'none'}">Show more options</button></div></div><div id="legend"></div><div id="cards"></div>`;geo('#g0',0);geo('#g1',1);bindLocationButtons();$('#more').onclick=()=>recommend(3,true);cards()}
function adventure(){st.mode='loop';panel.innerHTML=head('Adventure','Start and finish at current location with scenic, landmark and food suggestions')+`<div class="card"><div class="field"><label>Adventure start and finish</label><div class="location-row"><div id="ga" class="location-search"></div><button id="adventureHere" class="loc-btn" title="Use current location for adventure">◎</button></div><small class="muted">The adventure route returns to this location using a loop rather than the same out-and-back path.</small></div><div class="range-grid"><div class="field"><label>Distance <b id="dv">20 to 60 km</b></label><input id="dmin" type="range" min="5" max="100" value="20"><input id="dmax" type="range" min="10" max="160" value="60"></div><div class="field"><label>Elevation gain <b id="ev">0 to 900 m</b></label><input id="emin" type="range" min="0" max="1500" step="50" value="0"><input id="emax" type="range" min="100" max="3000" step="50" value="900"></div></div><div class="field"><label>Adventure preference</label><select id="pref"><option value="scenic">Beautiful views</option><option value="landmark">Well-known landmarks</option><option value="food">Good food stops</option><option value="mixed" selected>Balanced adventure</option></select></div><div class="actions"><button class="btn primary" id="recommend">Recommend 5 adventures</button><button class="btn light" id="more">Show 3 more</button></div></div><div id="legend"></div><div id="cards"></div>`;geo('#ga',0);$('#adventureHere').onclick=()=>setCurrentLocation(0,true);bindRanges();$('#recommend').onclick=()=>recommend(5,false);$('#more').onclick=()=>recommend(3,true);cards()}
function bindLocationButtons(){$('#startHere').onclick=()=>setCurrentLocation(0);$('#finishHere').onclick=()=>setCurrentLocation(1)}
async function setCurrentLocation(index,isAdventure=false){const p=await current();if(!p)return;let name='Current location';try{const d=await fetch(`https://api.mapbox.com/geocoding/v5/mapbox.places/${p[0]},${p[1]}.json?access_token=${MAPBOX_TOKEN}`).then(r=>r.json());name=d.features?.[0]?.place_name||name}catch(e){console.warn('Reverse geocoding failed',e)}st.waypoints[index]=p;st.names[index]=name;if(isAdventure){st.waypoints=[p,p];st.names=[name,name]}const key=isAdventure?'#ga':index?'#g1':'#g0',g=st.geocoders[key];if(g)g.setInput(name);syncMarkers();map.flyTo({center:p,zoom:14});toast(isAdventure?`Adventure starts and finishes at ${name}`:`${index?'Finish':'Start'} set to ${name}`);if(!isAdventure&&st.mode==='point'&&st.waypoints[0]&&st.waypoints[1])recommend(5,false)}
function bindRanges(){const update=()=>{$('#dv').textContent=`${$('#dmin').value} to ${$('#dmax').value} km`;$('#ev').textContent=`${$('#emin').value} to ${$('#emax').value} m`};['#dmin','#dmax','#emin','#emax'].forEach(x=>$(x).oninput=update)}
function geo(id,i){const adventure=id==='#ga',g=new MapboxGeocoder({accessToken:MAPBOX_TOKEN,mapboxgl,marker:false,placeholder:adventure?'Adventure start location':i?'Finish location':'Start location'});g.addTo(id);st.geocoders[id]=g;g.on('result',e=>{st.waypoints[i]=e.result.center;st.names[i]=e.result.place_name||e.result.text;syncMarkers();if(adventure){st.waypoints=[e.result.center,e.result.center];st.names=[st.names[i],st.names[i]]}if(st.mode==='point'&&st.waypoints[0]&&st.waypoints[1])recommend(5,false)})}
function constraints(){if(st.mode==='point')return{d0:0,d1:10000,e0:0,e1:100000,pref:'mixed'};return{d0:+$('#dmin').value,d1:+$('#dmax').value,e0:+$('#emin').value,e1:+$('#emax').value,pref:$('#pref').value}}
async function recommend(count,append){stopPreview();const c=constraints();if(st.mode==='loop'){const start=st.waypoints[0]||await current();if(!start)return;st.waypoints=[start,start];st.names=['Current location','Current location'];const extras=[];for(let i=0;i<count;i++){const target=c.d0+(c.d1-c.d0)*(i+1)/(count+1),radius=target/(2*Math.PI),angle=(i*137+st.routeBatch*43)%360,via1=turf.destination(start,radius,angle).geometry.coordinates,via2=turf.destination(start,radius,angle+120).geometry.coordinates,via3=turf.destination(start,radius,angle+240).geometry.coordinates;extras.push((async()=>{const poi=await findPOI(via1,c.pref,i),r=await fetchRoute([start,poi?.center||via1,via2,via3,start],`Adventure loop ${i+1}`);if(r&&poi){r.poi=poi.name;r.poiData=poi}return r})())}st.routeBatch++;await ingest(await Promise.all(extras),append,c)}else{if(st.waypoints.filter(Boolean).length<2)return toast('Choose start and finish');const base=await fetchAlternatives(st.waypoints);let all=[...base];const line=turf.lineString(st.waypoints),mid=turf.along(line,turf.length(line)/2).geometry.coordinates,bear=turf.bearing(st.waypoints[0],st.waypoints[1]),dist=turf.length(line);for(let i=0;all.length<count;i++){const off=turf.destination(mid,Math.min(12,dist*(.12+i*.04)),bear+(i%2?90:-90)).geometry.coordinates;const poi=await findPOI(off,c.pref,i),r=await fetchRoute([st.waypoints[0],poi?.center||off,st.waypoints[1]],`Adventure option ${all.length+1}`);if(r){if(poi){r.poi=poi.name;r.poiData=poi}all.push(r)}}await ingest(all.slice(0,count),append,c)}}
async function fetchAlternatives(p){try{const c=p.map(x=>x.join(',')).join(';'),d=await fetch(`https://api.mapbox.com/directions/v5/mapbox/cycling/${c}?alternatives=true&geometries=geojson&overview=full&steps=true&access_token=${MAPBOX_TOKEN}`).then(r=>r.json());return d.routes||[]}catch{return[]}}
async function fetchRoute(p,name){try{const c=p.map(x=>x.join(',')).join(';'),d=await fetch(`https://api.mapbox.com/directions/v5/mapbox/cycling/${c}?geometries=geojson&overview=full&steps=true&access_token=${MAPBOX_TOKEN}`).then(r=>r.json()),r=d.routes?.[0];if(r)r.name=name;return r}catch{return null}}
async function ingest(rs,append,c){toast('Analysing terrain and route highlights…');rs=rs.filter(Boolean);await Promise.all(rs.map(enrich));rs.forEach((r,i)=>{r.poi=r.poi||poiHint(r,c.pref,i);r.score=score(r,c)});rs=rs.filter(r=>(r.distance/1000)>=c.d0*.75&&(r.distance/1000)<=c.d1*1.25&&r.ascent>=c.e0&&r.ascent<=c.e1*1.25).sort((a,b)=>b.score-a.score);st.routes=append?[...st.routes,...rs]:rs;st.selected=null;drawAll();drawConsideredPOIs();cards();toast(`${st.routes.length} routes ready`)}
async function findPOI(near,pref,i){const terms={scenic:['viewpoint','country park','nature reserve'],landmark:['landmark','castle','monument'],food:['cafe','bakery','restaurant'],mixed:['viewpoint','landmark','cafe']},q=terms[pref][i%3];try{const d=await fetch(`https://api.mapbox.com/geocoding/v5/mapbox.places/${encodeURIComponent(q)}.json?types=poi&proximity=${near[0]},${near[1]}&limit=5&access_token=${MAPBOX_TOKEN}`).then(r=>r.json()),f=d.features?.find(x=>turf.distance(near,x.center)<15)||d.features?.[0];return f?{center:f.center,name:f.text||q}:null}catch{return null}}
function drawConsideredPOIs(){st.poiMarkers.forEach(m=>m.remove());st.poiMarkers=[];const seen=new Set();st.routes.forEach((r,i)=>{const p=r.poiData;if(!p||seen.has(p.name))return;seen.add(p.name);const el=document.createElement('button');el.className='poi-star';el.innerHTML='★';el.title=`Considered: ${p.name}`;const pop=new mapboxgl.Popup({offset:18}).setHTML(`<b>★ ${p.name}</b><br><small>Considered for route ${i+1}</small>`);const m=new mapboxgl.Marker({element:el}).setLngLat(p.center).setPopup(pop).addTo(map);st.poiMarkers.push(m)})}
function poiHint(r,pref,i){const pools={scenic:['riverside viewpoint','country park','woodland trail'],landmark:['historic landmark','castle or monument','famous local sight'],food:['popular café','bakery stop','well-rated food stop'],mixed:['scenic viewpoint','local landmark','popular café']};return pools[pref][i%3]}
function score(r,c){const d=r.distance/1000,mid=(c.d0+c.d1)/2,dm=Math.abs(d-mid),em=Math.max(0,r.ascent-c.e1)+Math.max(0,c.e0-r.ascent);return Math.max(0,100-dm*1.4-em*.04+(r.poi?8:0))}
async function enrich(r){const p=sample(r.geometry.coordinates,55);try{const d=await fetch(`https://api.open-meteo.com/v1/elevation?latitude=${p.map(x=>x[1])}&longitude=${p.map(x=>x[0])}`).then(x=>x.json());r.elev=d.elevation||[];r.ascent=gain(r.elev)}catch{r.elev=[];r.ascent=0}r.wind=Array.from({length:12},(_,i)=>Math.sin(i*.8)*st.wind.speed)}
function sample(c,n){if(c.length<=n)return c;const l=turf.lineString(c),d=turf.length(l);return Array.from({length:n},(_,i)=>turf.along(l,d*i/(n-1)).geometry.coordinates)}function gain(a){let g=0;for(let i=1;i<a.length;i++)if(a[i]>a[i-1])g+=a[i]-a[i-1];return g}
const colors=['#176bdb','#e34f4f','#16a36b','#f28b30','#8e5bd9','#00a6a6','#e64f98','#7d8b00'];function drawAll(){clearLayers();st.routes.forEach((r,i)=>addLine(`route-${i}`,r.geometry,colors[i%colors.length],i===0?7:5,.82));const geos={type:'FeatureCollection',features:st.routes.map(r=>({type:'Feature',geometry:r.geometry,properties:{}}))};if(st.routes.length){const b=turf.bbox(geos);map.fitBounds([[b[0],b[1]],[b[2],b[3]]],{padding:mobile()?45:{left:570,right:50,top:50,bottom:50}})}legend()}
function addLine(id,g,c,w,o){map.addSource(id,{type:'geojson',data:{type:'Feature',geometry:g,properties:{}}});map.addLayer({id,type:'line',source:id,layout:{'line-cap':'round','line-join':'round'},paint:{'line-color':c,'line-width':w,'line-opacity':o}});st.layers.push(id)}function clearLayers(){st.layers.forEach(id=>{if(map.getLayer(id))map.removeLayer(id);if(map.getSource(id))map.removeSource(id)});st.layers=[]}
function legend(){const e=$('#legend');if(!e)return;e.innerHTML=`<div class="route-key">${st.routes.map((r,i)=>`<span class="key"><i style="background:${colors[i%colors.length]}"></i>${i+1}</span>`).join('')}</div>`}
function cards(){const x=$('#cards');if(!x)return;if(!st.routes.length){x.innerHTML='<div class="empty">Generate routes to compare distance, climbing, food and views.</div>';return}x.innerHTML=st.routes.map((r,i)=>`<div class="card route ${st.selected===i?'selected':''}" data-i="${i}"><div class="row"><b>Route ${i+1}${i===0?' · Recommended':''}</b><span class="pill" style="background:${colors[i]}22;color:${colors[i]}">${Math.round(r.score)} score</span></div><div class="stats"><div class="stat"><b>${fmt(r.distance/1000)}</b><small>km</small></div><div class="stat"><b>${Math.round(r.duration/60)}</b><small>min</small></div><div class="stat"><b>${Math.round(r.ascent)}</b><small>elevation m</small></div><div class="stat"><b>${r.poi?'1+':'0'}</b><small>highlight</small></div></div><p><span class="pill poi">Suggested: ${r.poi}</span></p><div class="profiles"><div><div class="label">Elevation</div><canvas class="chart" data-e="${i}" width="430" height="130"></canvas></div><div><div class="label">Wind</div><canvas class="chart" data-w="${i}" width="430" height="130"></canvas></div></div></div>`).join('')+`<div class="actions"><button class="btn light" id="showAll">Show all</button><button class="btn primary" id="preview3d">3D preview</button><button class="btn green" id="save">Save selected</button></div>`;x.onclick=e=>{const r=e.target.closest('[data-i]');if(r)select(+r.dataset.i)};$('#showAll').onclick=()=>{st.selected=null;drawAll();cards()};$('#preview3d').onclick=preview3d;$('#save').onclick=save;requestAnimationFrame(charts)}
function select(i){stopPreview();st.selected=i;clearLayers();addLine('selected',st.routes[i].geometry,colors[i],8,1);st.route=st.routes[i];turnNodes();cards()}
function charts(){document.querySelectorAll('[data-e]').forEach(c=>plot(c,st.routes[+c.dataset.e].elev,'#16a36b'));document.querySelectorAll('[data-w]').forEach(c=>plot(c,st.routes[+c.dataset.w].wind,'#176bdb'))}function plot(c,a,col){const x=c.getContext('2d'),w=c.width,h=c.height;x.clearRect(0,0,w,h);if(!a.length)return;const lo=Math.min(...a),hi=Math.max(...a);x.strokeStyle=col;x.lineWidth=3;x.beginPath();a.forEach((v,i)=>{const px=5+i*(w-10)/(a.length-1),py=h-8-(v-lo)*(h-16)/(hi-lo||1);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()}
function turnNodes(){st.nodes.forEach(m=>m.remove());st.nodes=[];(st.route?.legs?.flatMap(l=>l.steps)||[]).slice(1,-1).forEach(s=>{const e=document.createElement('div');e.className='turn';const m=new mapboxgl.Marker({element:e,draggable:true}).setLngLat(s.maneuver.location).addTo(map);m.on('dragend',async()=>{const p=m.getLngLat().toArray(),r=await fetchRoute([st.route.geometry.coordinates[0],p,st.route.geometry.coordinates.at(-1)],st.route.name);if(r){await enrich(r);r.poi=st.route.poi;r.score=st.route.score;st.routes[st.selected]=r;st.route=r;select(st.selected);toast('Only this route changed')}});st.nodes.push(m)})}
function preview3d(){if(st.selected===null)return toast('Select a route');const run=++st.previewRun,c=sample(st.route.geometry.coordinates,70);let i=0;const go=()=>{if(run!==st.previewRun||i>=c.length-1)return;map.easeTo({center:c[i],bearing:turf.bearing(c[i],c[i+1]),pitch:65,zoom:17,duration:450});i++;st.previewTimer=setTimeout(go,470)};go()}
function save(){if(st.selected===null)return toast('Select a route');const a=store.get('routes'),name=prompt('Route name',st.mode==='loop'?'Adventure loop':`${st.names[0]||'Start'} to ${st.names[1]||'Finish'}`);if(!name)return;a.unshift({id:crypto.randomUUID(),name,route:st.route});store.set('routes',a);toast('Saved')}
function routes(){const a=store.get('routes');panel.innerHTML=head('Routes','Saved routes include distance and elevation gain')+`<div class="card">${a.length?a.map((r,i)=>`<div class="item" data-r="${i}"><div><b>${r.name}</b><div class="muted">${fmt(r.route.distance/1000)} km · ${Math.round(r.route.ascent||0)} m elevation</div></div><button class="btn primary">Open</button></div>`).join(''):'<div class="empty">No routes.</div>'}</div>`;panel.onclick=e=>{const row=e.target.closest('[data-r]');if(!row)return;st.routes=[a[+row.dataset.r].route];st.route=st.routes[0];st.selected=0;clearLayers();addLine('selected',st.route.geometry,colors[0],8,1);open(st.route.geometry.coordinates[0][0]===st.route.geometry.coordinates.at(-1)[0]&&st.route.geometry.coordinates[0][1]===st.route.geometry.coordinates.at(-1)[1]?'adventure':'journey')}}
function activities(){const a=store.get('activities');panel.innerHTML=head('Activities','Distance and elevation gain are shown for every activity')+`<div class="card">${a.length?a.map(x=>`<div class="item"><div><b>${x.name||'Ride'}</b><div class="muted">${fmt(x.distance)} km · ${Math.round(x.gain||0)} m elevation gain</div></div></div>`).join(''):'<div class="empty">No activities.</div>'}</div>`}
async function weather(){if(!st.weather)await loadWeather();const w=st.weather;panel.innerHTML=head('Weather','Current conditions, hourly forecast, radar and animated wind')+(w?`<div class="card wx-current"><div class="wx-symbol">${wxIcon(w.current.weather_code,w.current.is_day)}</div><div><h2>${Math.round(w.current.temperature_2m)}°C</h2><b>${wxText(w.current.weather_code)}</b><div class="muted">Feels ${Math.round(w.current.apparent_temperature)}° · wind ${Math.round(w.current.wind_speed_10m)} km/h · gust ${Math.round(w.current.wind_gusts_10m)} km/h</div></div></div><div class="card"><b>Next 18 hours</b><div class="hourly">${w.hourly.time.slice(0,18).map((t,i)=>`<div class="wx-hour"><small>${new Date(t).toLocaleTimeString([],{hour:'2-digit'})}</small><span>${wxIcon(w.hourly.weather_code[i],1)}</span><b>${Math.round(w.hourly.temperature_2m[i])}°</b><small>${w.hourly.precipitation_probability[i]}% rain</small><small>${Math.round(w.hourly.wind_speed_10m[i])} km/h</small></div>`).join('')}</div></div><div class="card"><div class="actions"><button class="btn primary" id="toggle">${st.weatherOn?'Hide':'Show'} radar + wind</button><button class="btn light" id="cycleRoutes">${st.cycleLayer?'Hide':'Show'} cycling routes</button></div><p class="muted">Wind particles follow the current wind direction. Cycling routes use a bicycle-focused OpenStreetMap overlay.</p></div>`:'<div class="empty">Weather is loading…</div>');if($('#toggle'))$('#toggle').onclick=toggleWeather;if($('#cycleRoutes'))$('#cycleRoutes').onclick=toggleCycleRoutes}
async function loadWeather(){const p=st.route?.geometry.coordinates[0]||map.getCenter().toArray();try{st.weather=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${p[1]}&longitude=${p[0]}&current=temperature_2m,apparent_temperature,weather_code,is_day,wind_speed_10m,wind_direction_10m,wind_gusts_10m&hourly=temperature_2m,precipitation_probability,weather_code,wind_speed_10m&timezone=auto&forecast_days=2`).then(r=>r.json());st.wind={speed:st.weather.current.wind_speed_10m,dir:st.weather.current.wind_direction_10m}}catch(e){console.error(e);toast('Weather unavailable')}}
function wxText(c){return c===0?'Clear sky':c<4?'Partly cloudy':c<50?'Fog':c<70?'Rain':c<80?'Snow':c<90?'Showers':'Thunderstorms'}
function wxIcon(c,day=1){if(c===0)return day?'☀️':'🌙';if(c<4)return'⛅';if(c<50)return'🌫️';if(c<70)return'🌧️';if(c<80)return'🌨️';if(c<90)return'🌦️';return'⛈️'}
function toggleCycleRoutes(){st.cycleLayer=!st.cycleLayer;if(st.cycleLayer){if(!map.getSource('cycle-routes'))map.addSource('cycle-routes',{type:'raster',tiles:['https://a.tile-cyclosm.openstreetmap.fr/cyclosm-lite/{z}/{x}/{y}.png','https://b.tile-cyclosm.openstreetmap.fr/cyclosm-lite/{z}/{x}/{y}.png','https://c.tile-cyclosm.openstreetmap.fr/cyclosm-lite/{z}/{x}/{y}.png'],tileSize:256,attribution:'CyclOSM © OpenStreetMap contributors'});if(!map.getLayer('cycle-routes'))map.addLayer({id:'cycle-routes',type:'raster',source:'cycle-routes',paint:{'raster-opacity':.68}})}else{if(map.getLayer('cycle-routes'))map.removeLayer('cycle-routes');if(map.getSource('cycle-routes'))map.removeSource('cycle-routes')}if(st.page==='weather')weather()}
function profile(){const routes=store.get('routes'),acts=store.get('activities');panel.innerHTML=head('Profile','Account, login and ride totals')+(st.user?`<div class="card"><div class="row"><img class="avatar" src="${st.user.photoURL||'icon.png'}"><div><b>${st.user.displayName||'Rider'}</b><div class="muted">${st.user.email||''}</div></div></div><button class="btn light" id="logout">Log out</button></div>`:`<div class="card"><h2>Sign in to Handry</h2><p class="muted">Login is required for cloud route sharing and collaborative live journeys.</p><button class="btn primary" id="login">Login with Google</button></div>`)+`<div class="stats"><div class="stat"><b>${routes.length}</b><small>routes</small></div><div class="stat"><b>${acts.length}</b><small>activities</small></div><div class="stat"><b>${acts.reduce((n,a)=>n+(a.distance||0),0).toFixed(0)}</b><small>km</small></div><div class="stat"><b>${Math.round(acts.reduce((n,a)=>n+(a.gain||0),0))}</b><small>elevation m</small></div></div>`;if($('#login'))$('#login').onclick=()=>st.login?st.login().catch(e=>toast(e.message)):toast('Authentication is loading');if($('#logout'))$('#logout').onclick=()=>st.logout?.()}
async function initAuth(){try{const[{initializeApp},{getAuth,GoogleAuthProvider,onAuthStateChanged,signInWithPopup,signOut}]=await Promise.all([import('https://www.gstatic.com/firebasejs/10.7.1/firebase-app.js'),import('https://www.gstatic.com/firebasejs/10.7.1/firebase-auth.js')]);const app=initializeApp(firebaseConfig);st.auth=getAuth(app);const provider=new GoogleAuthProvider();st.login=()=>signInWithPopup(st.auth,provider);st.logout=()=>signOut(st.auth);onAuthStateChanged(st.auth,u=>{st.user=u;if(st.page==='profile')profile()})}catch(e){console.error('Firebase auth unavailable',e)}}
initAuth()
async function toggleWeather(){st.weatherOn=!st.weatherOn;$('#wx').classList.toggle('active',st.weatherOn);if(st.weatherOn){if(!st.weather)await loadWeather();await radar();windStart()}else{radarOff();windStop()}if(st.page==='weather')weather()}
async function radar(){try{const d=await fetch('https://api.rainviewer.com/public/weather-maps.json').then(r=>r.json()),f=d.radar.past.at(-1);radarOff();map.addSource('radar',{type:'raster',tiles:[`${d.host}${f.path}/512/{z}/{x}/{y}/2/1_1.png`],tileSize:512,maxzoom:7});map.addLayer({id:'radar',type:'raster',source:'radar',paint:{'raster-opacity':.32}})}catch{toast('Radar unavailable')}}function radarOff(){if(map.getLayer('radar'))map.removeLayer('radar');if(map.getSource('radar'))map.removeSource('radar')}
let wf=0;function windStart(){const c=$('#wind'),ctx=c.getContext('2d'),wrap=$('#map-wrap'),d=devicePixelRatio||1;let r=wrap.getBoundingClientRect();c.width=Math.round(r.width*d);c.height=Math.round(r.height*d);ctx.setTransform(d,0,0,d,0,0);c.style.display='block';const count=mobile()?130:220,p=Array.from({length:count},()=>({x:Math.random()*r.width,y:Math.random()*r.height,a:Math.random()*120,len:8+Math.random()*16})),rad=(st.wind.dir+180)*Math.PI/180,v=Math.max(1.1,Math.min(3,st.wind.speed/9));cancelAnimationFrame(wf);const draw=()=>{r=wrap.getBoundingClientRect();ctx.clearRect(0,0,r.width,r.height);ctx.strokeStyle='rgba(80,210,255,.88)';ctx.lineWidth=1.25;p.forEach(q=>{const x=q.x,y=q.y;q.x+=Math.sin(rad)*v;q.y-=Math.cos(rad)*v;q.a++;ctx.beginPath();ctx.moveTo(x-Math.sin(rad)*q.len,y+Math.cos(rad)*q.len);ctx.lineTo(q.x,q.y);ctx.stroke();if(q.x<-25||q.y<-25||q.x>r.width+25||q.y>r.height+25||q.a>150){q.x=Math.random()*r.width;q.y=Math.random()*r.height;q.a=0}});wf=requestAnimationFrame(draw)};draw()}function windStop(){cancelAnimationFrame(wf);const c=$('#wind');c.style.display='none';c.getContext('2d').clearRect(0,0,c.width,c.height)}
async function current(){return new Promise(res=>navigator.geolocation?.getCurrentPosition(p=>res([p.coords.longitude,p.coords.latitude]),()=>{toast('Allow location access');res(null)},{enableHighAccuracy:true}))}function syncMarkers(){st.markers.forEach(m=>m.remove());st.markers=[];st.waypoints.filter(Boolean).forEach(p=>st.markers.push(new mapboxgl.Marker().setLngLat(p).addTo(map)))}
$('#locate').onclick=async()=>{const p=await current();if(p)map.flyTo({center:p,zoom:14})};$('#wx').onclick=toggleWeather;$('#styles').onclick=()=>{let m=$('.style-menu');if(m)return m.remove();m=document.createElement('div');m.className='style-menu';m.innerHTML=['outdoors-v12','streets-v12','satellite-streets-v12','navigation-night-v1'].map(s=>`<button data-s="${s}">${s.replaceAll('-',' ')}</button>`).join('');$('#map-wrap').appendChild(m);m.onclick=e=>{if(!e.target.dataset.s)return;map.setStyle(`mapbox://styles/mapbox/${e.target.dataset.s}`);map.once('style.load',()=>{if(st.selected===null)drawAll();else if(st.route){clearLayers();addLine('selected',st.route.geometry,colors[st.selected],8,1)}if(st.weatherOn)radar();if(st.cycleLayer){st.cycleLayer=false;toggleCycleRoutes()}});m.remove()}};
map.on('load',()=>open('explore'));addEventListener('resize',()=>{map.resize();if(st.weatherOn)windStart()});

if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(console.error);
